stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: scc/helloworldi:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
