stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancherspace/public:helloV1.0
      pushRemote: true
      registry: 127.0.0.1:34316
timeout: 60
notification: {}
