apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2020-11-27T05:47:11Z"
    cni.projectcalico.org/podIP: 10.42.0.32/32
    cni.projectcalico.org/podIPs: 10.42.0.32/32
    field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"hello-v1-nodeport","hostPort":0,"kind":"NodePort","name":"8080tcp1","protocol":"TCP"}]]'
  creationTimestamp: "2020-11-27T05:47:11Z"
  generateName: hello-v1-7ffd745d67-
  labels:
    pod-template-hash: 7ffd745d67
    workload.user.cattle.io/workloadselector: deployment-default-hello-v1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cattle.io/timestamp: {}
          f:field.cattle.io/ports: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:pod-template-hash: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"c01f562f-f3c4-4449-add8-9c78ea91757a"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"hello-v1"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:resources: {}
            f:securityContext:
              .: {}
              f:allowPrivilegeEscalation: {}
              f:capabilities: {}
              f:privileged: {}
              f:readOnlyRootFilesystem: {}
              f:runAsNonRoot: {}
            f:stdin: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:tty: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:imagePullSecrets:
          .: {}
          k:{"name":"dockerhub"}:
            .: {}
            f:name: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-11-27T05:47:11Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2020-11-27T05:47:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.42.0.32"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-11-27T05:47:43Z"
  name: hello-v1-7ffd745d67-8pqsj
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-v1-7ffd745d67
    uid: c01f562f-f3c4-4449-add8-9c78ea91757a
  resourceVersion: "51160"
  selfLink: /api/v1/namespaces/default/pods/hello-v1-7ffd745d67-8pqsj
  uid: 3895063d-e3c3-44fd-843f-8572b1ec038f
spec:
  containers:
  - image: 15221572751/public:latest
    imagePullPolicy: Always
    name: hello-v1
    ports:
    - containerPort: 8080
      name: 8080tcp1
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jwgk5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: dockerhub
  nodeName: rancher
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jwgk5
    secret:
      defaultMode: 420
      secretName: default-token-jwgk5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-11-27T05:47:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-11-27T05:47:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-11-27T05:47:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-11-27T05:47:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6c1e417cac9c9cdd85ca474bbed3b34d9dddde68e905e1bafc64a4019535fc34
    image: 15221572751/public:latest
    imageID: docker-pullable://15221572751/public@sha256:10b0b62ebeb260c90a1440e14
    490fd1b8b1557bea894102c1d7ff92c83e173a1
    lastState: {}
    name: hello-v1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-11-27T05:47:42Z"
  hostIP: 172.17.16.3
  phase: Running
  podIP: 10.42.0.32
  podIPs:
  - ip: 10.42.0.32
  qosClass: BestEffort
  startTime: "2020-11-27T05:47:11Z"
